"""update cache table

Revision ID: fc87fc99f4c3
Revises: 125b55cb2626
Create Date: 2025-06-06 12:46:53.262431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc87fc99f4c3'
down_revision: Union[str, None] = '125b55cb2626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_cache_key'), table_name='cache')
    op.create_index(op.f('ix_cache_key'), 'cache', ['key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cache_key'), table_name='cache')
    op.create_index(op.f('idx_cache_key'), 'cache', ['key'], unique=False)
    # ### end Alembic commands ###
