"""Add prompt model

Revision ID: 80fb1462938f
Revises: f63982f263eb
Create Date: 2025-06-09 17:25:23.120119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80fb1462938f'
down_revision: Union[str, None] = 'f63982f263eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt',
    sa.Column('prompt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.Text(length=256), nullable=False),
    sa.Column('prompt', sa.Text(length=8096), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prompt_id'),
    sqlite_autoincrement=True
    )
    op.create_index('idx_prompt_user_id', 'prompt', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_prompt_user_id', table_name='prompt')
    op.drop_table('prompt')
    # ### end Alembic commands ###
